### ISSUE TITLE
Forge Changes the Text in 1.20.1

### ISSUE THREAD

**Issue by Panzimy** [chylex/Minecraft-Window-Title#11]
This is a little my problem. But the minecraft changes the text from Sir Forge to Normal Text (Minecraft Forge 1.20.1) after Loading

**Comment by chylex** [comment]
There is no version of Custom Window Title that officially supports Forge with 1.20.1. Last version that supports Forge is for 1.20, then NeoForge for 1.20.2+.

**Comment by Panzimy** [comment]
> There is no version of Custom Window Title that officially supports Forge with 1.20.1. Last version that supports Forge is for 1.20, then NeoForge for 1.20.2+.

Yeah, but the on Forge the 1.20.1 code is like 1.20 code, it's like 1.20.5 and 1.20.6 there was only little changes I test the mod for 1.20 on 1.20.1 and I change the .toml file and the mod really changes the title. On Fabric it's the same. Thanks for reply. Panzimy.

**Comment by chylex** [comment]
I cannot reproduce the issue with 1.20.1 and Fabric.
