### ISSUE TITLE
The Fabric isn't having "Minecraft" for Client but "MinecarftClient"

### ISSUE THREAD

**Issue by Panzimy** [chylex/Minecraft-Window-Title#12]
Hello I write some errors but these was my bad in my mod. Here is the real problem what I found in code the Intelij IDEA find an error with "Minecarft.class" in mixins and "Minecraft" in CustomWindowTitle.java. The class Minecraft doesn't exist in Fabric you need to change it to "MinecraftClient" if you are using Intelij IDEA the IDEA will edit the import. If you aren't change import to "import net.minecraft.client.MinecraftClient;". Bye, Panzimy

**Comment by chylex** [comment]
The project uses Mojang mappings, not yarn mappings or whichever ones name that class `MinecraftClient`.

**Comment by Panzimy** [comment]
Yeah, I don't close this because it's good warning (for people what are using this in their mods)

**Comment by chylex** [comment]
There is no reason to keep it open, there is no issue with the mod.
