### ISSUE TITLE
Hi. This is not issue.

### ISSUE THREAD

**Issue by MDReal32** [chylex/Minecraft-Window-Title#2]
This is a offer. We can add custom variables to Name... From registry or from another mod. Custom variables.

**Comment by chylex** [comment]
What do you mean?

**Comment by MDReal32** [comment]
In another mod i set for example
(im not minecraft dev for that i can be error)
registry.minecraftwindowtitle.newRegistry("newvariable", "newvalue")
And then i in config file writes
title = "New Variable {newvariable}"
And title is changes to 'New Variable newvalue'

**Comment by chylex** [comment]
You can already do that via `TitleTokens.registerToken`

**Comment by MDReal32** [comment]
Thanks.
