### ISSUE TITLE
Red X in multiplayer menu when trying to join a forge server that doesnt have the mod

### ISSUE THREAD

**Issue by cpm9** [chylex/Minecraft-Window-Title#4]
`[10Jul2021 15:32:02.321] [Netty Client IO #3/INFO] [net.minecraftforge.fml.client.ClientHooks/CLIENTHOOKS]: Client has mods that are missing on server: [customwindowtitle]`

**Comment by cpm9** [comment]
@chylex could you please backport the fix (v1.1.1) to forge 1.16.5 I would really appreciate it thanks

**Comment by chylex** [comment]
Updated.
