### ISSUE TITLE
1.20 update

### ISSUE THREAD

**Issue by vico93** [chylex/Minecraft-Window-Title#7]
Does an 1.20 update (at least for Fabric) be on plans?

**Comment by chylex** [comment]
1.20 isn't out yet. When it is, I will update the mod.

**Comment by vico93** [comment]
> Owner

But rc1 is 🙃

**Comment by chylex** [comment]
I will upload the update soon, however since Mojang completely changed how window icons work I have decided to drop custom icons for now.

**Comment by vico93** [comment]
> I will upload the update soon, however since Mojang completely changed how window icons work I have decided to drop custom icons for now.

Actually i was ask about the custom icon feature, if this could interfere with [BetterIcon](https://github.com/DerpDerpling/BetterIcon) even without being activated. For the custom icon part i was going to switch to it because the new 1.20 is very confusing to me (same icon used by the launcher before the latest update where it was changed as well to a non-sense creeper banner).

**Comment by chylex** [comment]
It should not interfere with other icon mods.

Fabric version is under review, I found that Forge version just doesn't work so that will have to wait.
